backend: tensorflow
class_name: Sequential
config:
  layers:
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      batch_input_shape: !!python/tuple
      - null
      - 40
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_1
      trainable: true
      units: 64
      use_bias: true
  - class_name: Activation
    config:
      activation: relu
      dtype: float32
      name: activation_1
      trainable: true
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_2
      trainable: true
      units: 64
      use_bias: true
  - class_name: Activation
    config:
      activation: relu
      dtype: float32
      name: activation_2
      trainable: true
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_3
      trainable: true
      units: 32
      use_bias: true
  - class_name: Activation
    config:
      activation: linear
      dtype: float32
      name: activation_3
      trainable: true
  name: sequential_1
keras_version: 2.2.5
