backend: tensorflow
class_name: Model
config:
  input_layers:
  - - input_1
    - 0
    - 0
  - - input_2
    - 0
    - 0
  layers:
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple
      - null
      - 40
      dtype: float32
      name: input_1
      sparse: false
    inbound_nodes: []
    name: input_1
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_1
      trainable: true
      units: 64
      use_bias: true
    inbound_nodes:
    - - - input_1
        - 0
        - 0
        - {}
    name: dense_1
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_2
      trainable: true
      units: 64
      use_bias: true
    inbound_nodes:
    - - - dense_1
        - 0
        - 0
        - {}
    name: dense_2
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: uniform
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_3
      trainable: true
      units: 32
      use_bias: true
    inbound_nodes:
    - - - dense_2
        - 0
        - 0
        - {}
    name: dense_3
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple
      - null
      - 32
      dtype: float32
      name: input_2
      sparse: false
    inbound_nodes: []
    name: input_2
  - class_name: Multiply
    config:
      dtype: float32
      name: multiply_1
      trainable: true
    inbound_nodes:
    - - - dense_3
        - 0
        - 0
        - &id001 {}
      - - input_2
        - 0
        - 0
        - *id001
    name: multiply_1
  name: model_1
  output_layers:
  - - multiply_1
    - 0
    - 0
keras_version: 2.2.5
